# Generated by Django 6.0.4 on 2026-04-19 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_id', models.CharField(max_length=255, unique=True)),
                ('zip_name', models.CharField(max_length=255)),
                ('label', models.IntegerField(null=True)),
                ('label_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BlockSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=50)),
                ('n_trials', models.IntegerField()),
                ('rt_gaze_ms_mean', models.FloatField(null=True)),
                ('rt_gaze_ms_median', models.FloatField(null=True)),
                ('direction_error_rate', models.FloatField(null=True)),
                ('express_like_rate', models.FloatField(null=True)),
                ('target_reached_rate', models.FloatField(null=True)),
                ('time_to_target_ms_mean', models.FloatField(null=True)),
                ('gap_overlap_delta_rt_ms', models.FloatField(null=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.recording')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectQC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_s', models.FloatField(null=True)),
                ('gaze_rate_hz', models.FloatField(null=True)),
                ('worn_ratio', models.FloatField(null=True)),
                ('n_gaze_samples', models.IntegerField(null=True)),
                ('blink_rate_per_min', models.FloatField(null=True)),
                ('n_fixations', models.IntegerField(null=True)),
                ('fix_dur_ms_median', models.FloatField(null=True)),
                ('fix_dur_ms_mean', models.FloatField(null=True)),
                ('n_saccades', models.IntegerField(null=True)),
                ('sacc_amp_deg_mean', models.FloatField(null=True)),
                ('sacc_peak_px_s_mean', models.FloatField(null=True)),
                ('imu_gyro_rms', models.FloatField(null=True)),
                ('qc_flag_low_worn', models.IntegerField()),
                ('qc_flag_low_rate', models.IntegerField()),
                ('qc_flag_high_motion', models.IntegerField()),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.recording')),
            ],
        ),
        migrations.CreateModel(
            name='TrialMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=50)),
                ('trial_id', models.IntegerField()),
                ('onset_s', models.FloatField(null=True)),
                ('rt_gaze_ms', models.FloatField(null=True)),
                ('rt_found', models.IntegerField(null=True)),
                ('target_side', models.CharField(max_length=10, null=True)),
                ('response_dir', models.CharField(max_length=10, null=True)),
                ('direction_error', models.FloatField(null=True)),
                ('express_like', models.IntegerField(null=True)),
                ('target_reached', models.IntegerField(null=True)),
                ('time_to_target_ms', models.FloatField(null=True)),
                ('trial_duration_ms', models.FloatField(null=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.recording')),
            ],
        ),
    ]
