# Generated by Django 6.0.4 on 2026-04-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocksummary',
            name='rt_gaze_ms_std',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='subjectqc',
            name='recording_folder',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trialmetrics',
            name='accuracy_sector',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trialmetrics',
            name='choice_side',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trialmetrics',
            name='correct_side',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trialmetrics',
            name='cue_color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trialmetrics',
            name='decision_correct',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trialmetrics',
            name='decision_rt_gaze_ms',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trialmetrics',
            name='fix_dur_ms_mean_trial',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trialmetrics',
            name='fix_dur_ms_median_trial',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trialmetrics',
            name='n_large_jumps_to_target',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trialmetrics',
            name='n_steps_to_target',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trialmetrics',
            name='post_response_dx_px',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trialmetrics',
            name='qc_trial_valid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trialmetrics',
            name='rt_saccade_found',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trialmetrics',
            name='rt_saccade_ms',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trialmetrics',
            name='time_to_target_share',
            field=models.FloatField(null=True),
        ),
    ]
