# Generated by Django 6.0.4 on 2026-04-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_blocksummary_rt_gaze_ms_std_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialmetrics',
            name='label',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trialmetrics',
            name='label_text',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='trialmetrics',
            name='zip_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trialmetrics',
            name='zip_stem',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
