# Generated by Django 6.0.4 on 2026-04-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_trialmetrics_label_trialmetrics_label_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocksummary',
            name='label',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blocksummary',
            name='label_text',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='blocksummary',
            name='zip_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blocksummary',
            name='zip_stem',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
