# Generated by Django 6.0.4 on 2026-05-21 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_blocksummary_label_blocksummary_label_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimodalPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('p_eye', models.FloatField(help_text='P(patient) от Eye-классификатора', null=True)),
                ('p_speech', models.FloatField(help_text='P(patient) от Speech-классификатора', null=True)),
                ('w_eye', models.FloatField(default=0.5)),
                ('w_speech', models.FloatField(default=0.5)),
                ('p_fused', models.FloatField(null=True)),
                ('threshold', models.FloatField(default=0.5)),
                ('prediction', models.IntegerField(help_text='0=healthy, 1=patient', null=True)),
                ('label_text', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence', models.FloatField(null=True)),
                ('eye_model_name', models.CharField(default='RandomForest', max_length=100)),
                ('speech_model_name', models.CharField(default='SVM', max_length=100)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='pipeline.recording')),
            ],
            options={
                'verbose_name': 'Multimodal Prediction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeechRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fo_hz', models.FloatField(null=True, verbose_name='MDVP:Fo(Hz)')),
                ('fhi_hz', models.FloatField(null=True, verbose_name='MDVP:Fhi(Hz)')),
                ('flo_hz', models.FloatField(null=True, verbose_name='MDVP:Flo(Hz)')),
                ('jitter_pct', models.FloatField(null=True, verbose_name='MDVP:Jitter(%)')),
                ('jitter_abs', models.FloatField(null=True, verbose_name='MDVP:Jitter(Abs)')),
                ('rap', models.FloatField(null=True, verbose_name='MDVP:RAP')),
                ('ppq', models.FloatField(null=True, verbose_name='MDVP:PPQ')),
                ('jitter_ddp', models.FloatField(null=True, verbose_name='Jitter:DDP')),
                ('shimmer', models.FloatField(null=True, verbose_name='MDVP:Shimmer')),
                ('shimmer_db', models.FloatField(null=True, verbose_name='MDVP:Shimmer(dB)')),
                ('shimmer_apq3', models.FloatField(null=True, verbose_name='Shimmer:APQ3')),
                ('shimmer_apq5', models.FloatField(null=True, verbose_name='Shimmer:APQ5')),
                ('mdvp_apq', models.FloatField(null=True, verbose_name='MDVP:APQ')),
                ('shimmer_dda', models.FloatField(null=True, verbose_name='Shimmer:DDA')),
                ('nhr', models.FloatField(null=True, verbose_name='NHR')),
                ('hnr', models.FloatField(null=True, verbose_name='HNR')),
                ('rpde', models.FloatField(null=True, verbose_name='RPDE')),
                ('dfa', models.FloatField(null=True, verbose_name='DFA')),
                ('spread1', models.FloatField(null=True, verbose_name='spread1')),
                ('spread2', models.FloatField(null=True, verbose_name='spread2')),
                ('ppe', models.FloatField(null=True, verbose_name='PPE')),
                ('status', models.IntegerField(help_text='0=healthy, 1=patient', null=True)),
                ('label_text', models.CharField(blank=True, max_length=50, null=True)),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speech_records', to='pipeline.recording')),
            ],
            options={
                'verbose_name': 'Speech Record',
                'ordering': ['-created_at'],
            },
        ),
    ]
