# Generated by Django 6.0.4 on 2026-05-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_multimodalprediction_speechrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='label',
            field=models.IntegerField(blank=True, help_text='0=healthy, 1=patient. Опционально.', null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='label_text',
            field=models.CharField(blank=True, default='', help_text='healthy / patient / unknown', max_length=50),
        ),
    ]
