# Generated by Django 6.0.4 on 2026-05-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0006_alter_recording_label_alter_recording_label_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speechrecord',
            options={},
        ),
        migrations.RenameField(
            model_name='speechrecord',
            old_name='recording',
            new_name='recording_id',
        ),
        migrations.RemoveField(
            model_name='speechrecord',
            name='created_at',
        ),
    ]
