# Generated by Django 6.0.4 on 2026-05-22 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0007_alter_speechrecord_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speechrecord',
            old_name='recording_id',
            new_name='recording',
        ),
    ]
