# Generated by Django 6.0.4 on 2026-06-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_rename_recording_id_speechrecord_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimodalprediction',
            name='modality_used',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='multimodalprediction',
            name='eye_model_name',
            field=models.CharField(default='SVM', max_length=100),
        ),
    ]
